name: Pin OpenTofu module dependencies
description: >-
  Pins dependencies and stores them in a
  [GitHub Actions workflow artifact](https://docs.github.com/en/actions/concepts/workflows-and-actions/workflow-artifacts),
  an immutable archive, which facilitates reproducible builds.  Run
  this action after pre-commit in the same workflow job.

inputs:
  artifact-name:
    description: >-
      The name of the immutable archive that will contain the
      dependency pins.
    required: true
    default: tofu-providers-lock-artifacts

runs:
  using: composite
  steps:
    - shell: bash
      run: tofu init
    - shell: bash
      run:
        tofu providers lock
        --platform=windows_amd64
        --platform=darwin_arm64
        --platform=linux_amd64
        --platform=linux_arm64
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.artifact-name }}
        path: .terraform.lock.hcl
        if-no-files-found: error
        include-hidden-files: true
