# This work is marked CC0 1.0 Universal.  To view a copy of this mark,
# visit https://creativecommons.org/publicdomain/zero/1.0/.

# NOTE: Keep documentation in sync with docs/python-freeze.md.

name: Pin Python project dependencies.
description: >-
  Pin dependencies and store them in a
  [GitHub Actions workflow artifact](https://docs.github.com/actions/concepts/workflows-and-actions/workflow-artifacts),
  an immutable archive, which facilitates reproducible builds.  This
  action assumes that Python is installed and that private repository
  access has been established (if needed), e.g., as if run after the
  [pre-commit](pre-commit) action in the same workflow job.

  To update the pinned version of pip-compile, remove
  [python-freeze/requirements.txt](github:python-freeze/requirements.txt)
  and regenerate it with the command `pip-compile --generate-hashes
  --allow-unsafe --uploaded-prior-to=P7D`, run from the
  [python-freeze/](github:python-freeze/) directory.

inputs:
  artifact-name:
    required: true
    default: pip-compile-artifacts
    description: >-
      This names the workflow artifact containing the dependency pins.

runs:
  using: composite
  steps:
    - name: Install pip-tools.
      shell: bash
      run: pip install -r "${GITHUB_ACTION_PATH}/requirements.txt" --require-hashes
    - name: Generate dependency pins.
      shell: bash
      run: pip-compile --generate-hashes --allow-unsafe --uploaded-prior-to=P7D
    - name: Upload Python package dependency pins to artifact storage.
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.artifact-name }}
        path: requirements.txt
        if-no-files-found: error
